### ISSUE TITLE
数据集该如何设置？

### ISSUE THREAD

**Issue by luyiwen-user** [hzwer/ECCV2022-RIFE#362]

**Comment by luyiwen-user** [comment]
![image](https://github.com/hzwer/ECCV2022-RIFE/assets/81129278/7fb2ef17-5fa9-4012-b002-4675f1e968d2)

**Comment by hzwer** [comment]
需要先从 http://toflow.csail.mit.edu 下载数据集

**Comment by pengjunxing** [comment]
> ![图像](https://private-user-images.githubusercontent.com/81129278/324159074-2feb0802-9897-4da1-bb66-02056761d8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjEzMjcsIm5iZiI6MTcyMTQ2MTAyNywicGF0aCI6Ii84MTEyOTI3OC8zMjQxNTkwNzQtMmZlYjA4MDItOTg5Ny00ZGExLWJiNjYtMDIwNTY3NjFkOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA3MzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYTFmODg0MDI1YmUyNGZiYWFjMmQzZDNiNmIwYTRmZmM3OTM1OTViYWE1MTNhZmExZWU4YjRiOWRkOGI4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eUF50c7IlFBME8BBy_JMnwmiWYZZiuOvjAlM1iKUfR4)

May I ask if you have replicated the training project, my friend? I would like to inquire about your environment version and what version of PyTorch, CUDA... you are using;


I encountered an issue while attempting to replicate the project:
(RIFE)  gzdx@gzdx-Super-Server :~/RIFE$ python3 -m torch.distributed.launch --nproc_per_node=4 train.py --world_size=2
/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead.  See 
https://pytorch.org/docs/stable/distributed.html#launch -utility  for 
further instructions

warnings.warn(
W0720 01:05:05.369797 140192998098752 torch/distributed/run.py:757] 
W0720 01:05:05.369797 140192998098752 torch/distributed/run.py:757] *****************************************
W0720 01:05:05.369797 140192998098752 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0720 01:05:05.369797 140192998098752 torch/distributed/run.py:757] *****************************************
usage: train.py [-h] [--epoch EPOCH] [--batch_size BATCH_SIZE] [--local_rank LOCAL_RANK] [--world_size WORLD_SIZE]
train.py: error: unrecognized arguments: --local-rank=3
usage: train.py [-h] [--epoch EPOCH] [--batch_size BATCH_SIZE] [--local_rank LOCAL_RANK] [--world_size WORLD_SIZE]
train.py: error: unrecognized arguments: --local-rank=1
usage: train.py [-h] [--epoch EPOCH] [--batch_size BATCH_SIZE] [--local_rank LOCAL_RANK] [--world_size WORLD_SIZE]
train.py: error: unrecognized arguments: --local-rank=2
usage: train.py [-h] [--epoch EPOCH] [--batch_size BATCH_SIZE] [--local_rank LOCAL_RANK] [--world_size WORLD_SIZE]
train.py: error: unrecognized arguments: --local-rank=0
E0720 01:05:10.407284 140192998098752 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 2) local_rank: 0 (pid: 301895) of binary: /home/gzdx/anaconda3/envs/RIFE/bin/python3
Traceback (most recent call last):
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/runpy.py",  line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/runpy.py",  line 87, in _run_code
exec(code, run_globals)
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/distributed/launch.py",  line 198, in <module>
main()
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/distributed/launch.py", line 194, in main
launch(args)
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/distributed/launch.py", line 179, in launch
run(args)
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/distributed/run.py", line 870, in run
elastic_launch(
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/distributed/launcher/api.py",  line 132, in __call__
return launch_agent(self._ config, self._entrypoint, list(args))
File "/home/gzdx/anaconda3/envs/RIFE/lib/python3.8/site-packages/torch/distributed/launcher/api.py",  line 263, in launch_agent
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
time      : 2024-07-20_01:05:10
host      : gzdx-Super-Server
rank      : 1 (local_rank: 1)
exitcode  : 2 (pid: 301896)
error_file: <N/A>
traceback : To enable traceback see:  https://pytorch.org/docs/stable/elastic/errors.html  
[2]:
time      : 2024-07-20_01:05:10
host      : gzdx-Super-Server
rank      : 2 (local_rank: 2)
exitcode  : 2 (pid: 301897)
error_file: <N/A>
traceback : To enable traceback see:  https://pytorch.org/docs/stable/elastic/errors.html  
[3]:
time      : 2024-07-20_01:05:10
host      : gzdx-Super-Server
rank      : 3 (local_rank: 3)
exitcode  : 2 (pid: 301898)
error_file: <N/A>
traceback : To enable traceback see:  https://pytorch.org/docs/stable/elastic/errors.html  
------------------------------------------------------------
Root Cause (first observed failure):
0
time      : 2024-07-20_01:05:10
host      : gzdx-Super-Server
rank      : 0 (local_rank: 0)
exitcode  : 2 (pid: 301895)
error_file: <N/A>
traceback : To enable traceback see:  https://pytorch.org/docs/stable/elastic/errors.html  
============================================================

**Comment by kike-0304** [comment]
> 需要先从 http://toflow.csail.mit.edu 下载数据集

自己制作专用的数据集用于微调可行吗

**Comment by hzwer** [comment]
@kike-0304 当然可以呀

**Comment by Felix3322** [comment]
这是自动回复，不代表作者观点。
由于该问题长期无实质性跟进且暂无新的可执行信息，先自动关闭此 issue。
如需重新开启，请回复 $reopen 并补充最新复现信息/日志。
如需作者人工介入，请直接 @hzwer。
