### ISSUE TITLE
RuntimeError: unexpected keys in state_dict when loading RIFE model

### ISSUE THREAD

**Issue by YANG-success-last** [hzwer/ECCV2022-RIFE#383]
在推理时，报错显示 权重加载时参数丢失。
使用以下代码加载模型：
   ```python
   from model.RIFE import Model
   model = Model()
   model.load_model("train_log", -1)
执行脚本后，报错如下：
Traceback (most recent call last):
  File "/home/liran001/RIFE/inference_img.py", line 29, in <module>
    model.load_model(params["modelDir"], -1)  # 加载权重
  File "/home/liran001/RIFE/model/RIFE.py", line 55, in load_model
    self.flownet.load_state_dict(convert(torch.load('{}/flownet.pkl'.format(path))))
  File "/home/liran001/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for IFNet:
        Missing key(s) in state_dict: "block0.conv0.0.0.weight", "block0.conv0.0.0.bias", "block0.conv0.0.1.weight", "block0.conv0.1.0.weight", "block0.conv0.1.0.bias", "block0.conv0.1.1.weight", "block0.convblock.0.0.weight", "block0.convblock.0.0.bias", "block0.convblock.0.1.weight", "block0.convblock.1.0.weight", "block0.convblock.1.0.bias", "block0.convblock.1.1.weight", "block0.convblock.2.0.weight", "block0.convblock.2.0.bias", "block0.convblock.2.1.weight", "block0.convblock.3.0.weight", "block0.convblock.3.0.bias", "block0.convblock.3.1.weight", "block0.convblock.4.0.weight", "block0.convblock.4.0.bias", "block0.convblock.4.1.weight", "block0.convblock.5.0.weight", "block0.convblock.5.0.bias", "block0.convblock.5.1.weight", "block0.convblock.6.0.weight", "block0.convblock.6.0.bias", "block0.convblock.6.1.weight", "block0.convblock.7.0.weight", "block0.convblock.7.0.bias", "block0.convblock.7.1.weight", "block0.lastconv.weight", "block0.lastconv.bias", "block1.conv0.0.0.weight", "block1.conv0.0.0.bias", "block1.conv0.0.1.weight", "block1.conv0.1.0.weight", "block1.conv0.1.0.bias", "block1.conv0.1.1.weight", "block1.convblock.0.0.weight", "block1.convblock.0.0.bias", "block1.convblock.0.1.weight", "block1.convblock.1.0.weight", "block1.convblock.1.0.bias", "block1.convblock.1.1.weight", "block1.convblock.2.0.weight", "block1.convblock.2.0.bias", "block1.convblock.2.1.weight", "block1.convblock.3.0.weight", "block1.convblock.3.0.bias", "block1.convblock.3.1.weight", "block1.convblock.4.0.weight", "block1.convblock.4.0.bias", "block1.convblock.4.1.weight", "block1.convblock.5.0.weight", "block1.convblock.5.0.bias", "block1.convblock.5.1.weight", "block1.convblock.6.0.weight", "block1.convblock.6.0.bias", "block1.convblock.6.1.weight", "block1.convblock.7.0.weight", "block1.convblock.7.0.bias", "block1.convblock.7.1.weight", "block1.lastconv.weight", "block1.lastconv.bias", "block2.conv0.0.0.weight", "block2.conv0.0.0.bias", "block2.conv0.0.1.weight", "block2.conv0.1.0.weight", "block2.conv0.1.0.bias", "block2.conv0.1.1.weight", "block2.convblock.0.0.weight", "block2.convblock.0.0.bias", "block2.convblock.0.1.weight", "block2.convblock.1.0.weight", "block2.convblock.1.0.bias", "block2.convblock.1.1.weight", "block2.convblock.2.0.weight", "block2.convblock.2.0.bias", "block2.convblock.2.1.weight", "block2.convblock.3.0.weight", "block2.convblock.3.0.bias", "block2.convblock.3.1.weight", "block2.convblock.4.0.weight", "block2.convblock.4.0.bias", "block2.convblock.4.1.weight", "block2.convblock.5.0.weight", "block2.convblock.5.0.bias", "block2.convblock.5.1.weight", "block2.convblock.6.0.weight", "block2.convblock.6.0.bias", "block2.convblock.6.1.weight", "block2.convblock.7.0.weight", "block2.convblock.7.0.bias", "block2.convblock.7.1.weight", "block2.lastconv.weight", "block2.lastconv.bias", "block_tea.conv0.0.0.weight", "block_tea.conv0.0.0.bias", "block_tea.conv0.0.1.weight", "block_tea.conv0.1.0.weight", "block_tea.conv0.1.0.bias", "block_tea.conv0.1.1.weight", "block_tea.convblock.0.0.weight", "block_tea.convblock.0.0.bias", "block_tea.convblock.0.1.weight", "block_tea.convblock.1.0.weight", "block_tea.convblock.1.0.bias", "block_tea.convblock.1.1.weight", "block_tea.convblock.2.0.weight", "block_tea.convblock.2.0.bias", "block_tea.convblock.2.1.weight", "block_tea.convblock.3.0.weight", "block_tea.convblock.3.0.bias", "block_tea.convblock.3.1.weight", "block_tea.convblock.4.0.weight", "block_tea.convblock.4.0.bias", "block_tea.convblock.4.1.weight", "block_tea.convblock.5.0.weight", "block_tea.convblock.5.0.bias", "block_tea.convblock.5.1.weight", "block_tea.convblock.6.0.weight", "block_tea.convblock.6.0.bias", "block_tea.convblock.6.1.weight", "block_tea.convblock.7.0.weight", "block_tea.convblock.7.0.bias", "block_tea.convblock.7.1.weight", "block_tea.lastconv.weight", "block_tea.lastconv.bias", "contextnet.conv1.conv1.0.weight", "contextnet.conv1.conv1.0.bias", "contextnet.conv1.conv1.1.weight", "contextnet.conv1.conv2.0.weight", "contextnet.conv1.conv2.0.bias", "contextnet.conv1.conv2.1.weight", "contextnet.conv2.conv1.0.weight", "contextnet.conv2.conv1.0.bias", "contextnet.conv2.conv1.1.weight", "contextnet.conv2.conv2.0.weight", "contextnet.conv2.conv2.0.bias", "contextnet.conv2.conv2.1.weight", "contextnet.conv3.conv1.0.weight", "contextnet.conv3.conv1.0.bias", "contextnet.conv3.conv1.1.weight", "contextnet.conv3.conv2.0.weight", "contextnet.conv3.conv2.0.bias", "contextnet.conv3.conv2.1.weight", "contextnet.conv4.conv1.0.weight", "contextnet.conv4.conv1.0.bias", "contextnet.conv4.conv1.1.weight", "contextnet.conv4.conv2.0.weight", "contextnet.conv4.conv2.0.bias", "contextnet.conv4.conv2.1.weight", "unet.down0.conv1.0.weight", "unet.down0.conv1.0.bias", "unet.down0.conv1.1.weight", "unet.down0.conv2.0.weight", "unet.down0.conv2.0.bias", "unet.down0.conv2.1.weight", "unet.down1.conv1.0.weight", "unet.down1.conv1.0.bias", "unet.down1.conv1.1.weight", "unet.down1.conv2.0.weight", "unet.down1.conv2.0.bias", "unet.down1.conv2.1.weight", "unet.down2.conv1.0.weight", "unet.down2.conv1.0.bias", "unet.down2.conv1.1.weight", "unet.down2.conv2.0.weight", "unet.down2.conv2.0.bias", "unet.down2.conv2.1.weight", "unet.down3.conv1.0.weight", "unet.down3.conv1.0.bias", "unet.down3.conv1.1.weight", "unet.down3.conv2.0.weight", "unet.down3.conv2.0.bias", "unet.down3.conv2.1.weight", "unet.up0.0.weight", "unet.up0.0.bias", "unet.up0.1.weight", "unet.up1.0.weight", "unet.up1.0.bias", "unet.up1.1.weight", "unet.up2.0.weight", "unet.up2.0.bias", "unet.up2.1.weight", "unet.up3.0.weight", "unet.up3.0.bias", "unet.up3.1.weight", "unet.conv.weight", "unet.conv.bias".

**Comment by hzwer** [comment]
那 torch.load('{}/flownet.pkl'.format(path)).keys() 会得到什么？

**Comment by hzwer** [comment]
我不理解，看起来模型参数和 pkl 中是一致的 #PyTorch模型加载错误解决方法# 来自跃问分享 https://yuewen.cn/share/179863116760768512?utm_source=share&utm_content=web_linkcopy&version=2
很奇怪的问题

**Comment by YANG-success-last** [comment]
好的谢谢，问题出在没有正确将模型参数导入推理中，已解决。

**Comment by YANG-success-last** [comment]
好的谢谢，问题出在没有正确将模型参数导入推理中，已解决。

**Comment by YANG-success-last** [comment]
好的非常感谢，问题出在没有正确将模型参数导入推理中，已解决。

**Comment by HornyMothmanEX** [comment]
how did you fixed

**Comment by Felix3322** [comment]
这是自动回复，不代表作者观点。
由于该问题长期无实质性跟进且暂无新的可执行信息，先自动关闭此 issue。
如需重新开启，请回复 $reopen 并补充最新复现信息/日志。
如需作者人工介入，请直接 @hzwer。
